import { z } from 'zod'

export const DetailPodcastSchema = z.object({
  wrapperType: z.string(),
  kind: z.string(),
  artistId: z.number(),
  collectionId: z.number(),
  trackId: z.number(),
  artistName: z.string(),
  collectionName: z.string(),
  trackName: z.string(),
  collectionCensoredName: z.string(),
  trackCensoredName: z.string(),
  artistViewUrl: z.string(),
  collectionViewUrl: z.string(),
  feedUrl: z.string(),
  trackViewUrl: z.string(),
  artworkUrl30: z.string(),
  artworkUrl60: z.string(),
  artworkUrl100: z.string(),
  collectionPrice: z.number(),
  trackPrice: z.number(),
  collectionHdPrice: z.number(),
  releaseDate: z.string(),
  collectionExplicitness: z.string(),
  trackExplicitness: z.string(),
  trackCount: z.number(),
  trackTimeMillis: z.number(),
  country: z.string(),
  currency: z.string(),
  primaryGenreName: z.string(),
  contentAdvisoryRating: z.string(),
  artworkUrl600: z.string(),
  genreIds: z.array(z.string()),
  genres: z.array(z.string()),
})

export const EpisodeSchema = z.object({
  country: z.string(),
  trackTimeMillis: z.number(),
  episodeContentType: z.string(),
  collectionViewUrl: z.string(),
  episodeFileExtension: z.string(),
  artworkUrl600: z.string(),
  closedCaptioning: z.string(),
  collectionId: z.number(),
  collectionName: z.string(),
  description: z.string(),
  shortDescription: z.string(),
  releaseDate: z.string(),
  feedUrl: z.string(),
  artistIds: z.array(z.number()),
  trackId: z.number(),
  trackName: z.string(),
  previewUrl: z.string(),
  episodeUrl: z.string(),
  artworkUrl60: z.string(),
  artistViewUrl: z.string(),
  contentAdvisoryRating: z.string(),
  trackViewUrl: z.string(),
  artworkUrl160: z.string(),
  kind: z.string(),
  wrapperType: z.string(),
  genres: z.array(z.object({ name: z.string(), id: z.string() })),
  episodeGuid: z.string(),
})

export type ResponseEpisode = z.infer<typeof EpisodeSchema>
export type ResponseDetailPodcast = z.infer<typeof DetailPodcastSchema>
